### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat 'C:/Program Files\Java\jdk1.8.0_241\bin;'

### ISSUE THREAD

**Issue by AloTheo** [spring-projects/atom-spring-boot#4]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.44.0 x64
**Electron**: 4.2.7
**OS**: Unknown Windows version
**Thrown From**: [spring-boot](https://github.com/spring-projects/atom-spring-boot) package 1.8.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Program Files\Java\jdk1.8.0_241\bin;'

```
At fs.js:115

Error: ENOENT: no such file or directory, lstat 'C:\Program Files\Java\jdk1.8.0_241\bin;'
    at Object.realpathSync (fs.js:1435:7)
    at Object.fs.realpathSync (ELECTRON_ASAR.js:306:40)
    at findJavaExe (/packages/spring-boot/node_modules/@pivotal-tools/jvm-launch-utils/lib/jvm-util.js:74:23)
    at findJvm (/packages/spring-boot/node_modules/@pivotal-tools/jvm-launch-utils/lib/jvm-util.js:17:19)
    at Object.findJdk (/packages/spring-boot/node_modules/@pivotal-tools/jvm-launch-utils/lib/jvm-util.js:29:12)
    at SpringBootLanguageClient.findJvm (/packages/spring-boot/node_modules/@pivotal-tools/atom-languageclient-commons/build/java-process-language-client.js:110:54)
    at SpringBootLanguageClient.launchProcess (/packages/spring-boot/node_modules/@pivotal-tools/atom-languageclient-commons/build/java-process-language-client.js:113:21)
    at Server.server.listen (/packages/spring-boot/node_modules/@pivotal-tools/atom-languageclient-commons/build/java-process-language-client.js:51:26)
    at Object.onceWrapper (events.js:273:13)
    at Server.emit (events.js:182:13)
    at emitListeningNT (net.js:1320:10)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

### Commands

```
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
atom-maven 1.3.2 
autocomplete-java 1.2.7 
ide-java 0.9.0 
platformio-ide-terminal 2.10.0 
script 3.25.0 
spring-boot 1.8.0 
```

**Comment by BoykoAlex** [comment]
We do not support Atom extensions anymore... this problem however is something about JVM not being located where it should be... Is your JVM at this location?
