### ISSUE TITLE
Failed to activate the spring-boot package

### ISSUE THREAD

**Issue by thiemaaliou** [spring-projects/atom-spring-boot#5]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: Unknown Windows version
**Thrown From**: [spring-boot](https://github.com/spring-projects/atom-spring-boot) package 1.20.0

### Stack Trace

Failed to activate the spring-boot package

```
At Cannot find module '@pivotal-tools/atom-languageclient-commons'
Require stack:
- C:\Users\LENOVO\.atom\packages\atom-spring-boot-master\build\spring-boot-language-client.js
- C:\Users\LENOVO\.atom\packages\atom-spring-boot-master\build\main.js
- C:\Users\LENOVO\AppData\Local\atom\app-1.53.0\resources\app.asar\static\index.html

Error: Cannot find module '@pivotal-tools/atom-languageclient-commons'
Require stack:
- C:\Users\LENOVO\.atom\packages\atom-spring-boot-master\build\spring-boot-language-client.js
- C:\Users\LENOVO\.atom\packages\atom-spring-boot-master\build\main.js
- C:\Users\LENOVO\AppData\Local\atom\app-1.53.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.53.0/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:155481)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:146814)
    at /packages/atom-spring-boot-master/build/spring-boot-language-client.js:4:39)
    at /packages/atom-spring-boot-master/build/spring-boot-language-client.js:66:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:146814)
    at /packages/atom-spring-boot-master/build/main.js:3:39)
    at /packages/atom-spring-boot-master/build/main.js:6:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:16:16)
    at customRequire (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:1:736531)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:3711337)
    at Package.activateNow (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:3699321)
    at ~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:3699099
    at Package.measure (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:3696677)
    at ~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:3698959
    at new Promise (<anonymous>)
    at Package.activate (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:3698902)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:383522)
```

### Commands

```
```

### Non-Core Packages

```
angular-2-typeScript-snippets 0.7.0 
atom-ide-terminal-master undefined 
atom-ide-ui 0.13.0 
atom-material-ui 2.1.3 
spring-boot 1.20.0 
atom-terminal 0.8.0 
atom-typescript 14.0.3 
autoclose-html 0.23.0 
color-picker 2.3.0 
git-control 0.9.0 
git-plus 8.7.1 
Hydrogen 2.13.1 
ide-java 0.9.1 
ide-typescript 0.9.1 
ionic-framework-snippets 1.2.1 
ionic-preview 0.7.0 
language-blade 0.46.0 
language-kotlin 0.5.0 
laravel 0.7.1 
nuclide-format-js 0.0.47 
split-diff 1.6.1 
```

**Comment by BoykoAlex** [comment]
Spring Boot Tools are not supported on Atom anymore. Please try either VSCode, Theia oe Eclipse
